steps:
- name: node
  entrypoint: npm
  args: ['install','test','run', 'build']
  
- name: maven:latest
  entrypoint: mvn
  args: ['test','compile']
  
- name: docker:latest
  args: ['build', '-t', 'tsiodocker/demojavascript:1.0', '.']
  args: ['push','tsiodocker/demojavascript:1.0']


