steps:
- name: node
  entrypoint: npm
  args: ['install']
  
- name: node
  entrypoint: npm
  args: ['test']


- name: docker:latest
  args: ['build', '-t', 'tsiodocker/demojavascript:1.0', '.']
  
  
- name: docker:latest
  args: ['push', 'tsiodocker/demojavascript:1.0']



