 steps:
 - name: maven:latest
   entrypoint: mvn 
   args: ['test','compile']
   
 
- name: node
  entrypoint: npm
  args: ['install',test','run','build]
  

- name: docker:latest
  args: ['build', '-t', 'tsiodocker/demojavat:1.0', '.']
  
  
- name: docker:latest
  args: ['push', 'tsiodocker/demojava:1.0']
  
- name: docker:latest
  args: ['build','-t', './node/tsiodocker/demojavascript:1.0', '.']
  
- name: docker:latest
  args: ['push', './node/tsiodocker/demojavascript:1.0']



