 steps:
 - name: maven:latest
   entrypoint: mvn 
   args: ['test']
   
 - name: maven:latest
   entrypoint: mvn
   args: [clean install]
 
  - name: node:latest
   entrypoint: cd
   args: [node]
   



